---
- name: Skapa grupper
  group:
    name: "{{ item.name }}"
    gid: "{{ item.gid }}"
    state: present
  loop:
    - { name: gemensam,    gid: 2000 }
    - { name: avdelning-a, gid: 2001 }
    - { name: avdelning-b, gid: 2002 }

- name: Skapa användare
  user:
    name: "{{ item.name }}"
    uid: "{{ item.uid }}"
    groups: "{{ item.groups }}"
    shell: /bin/bash
    state: present
    create_home: true
  loop:
    - { name: user-a1, uid: 2101, groups: ["avdelning-a", "gemensam"] }
    - { name: user-a2, uid: 2102, groups: ["avdelning-a", "gemensam"] }
    - { name: user-b1, uid: 2103, groups: ["avdelning-b", "gemensam"] }
    - { name: user-b2, uid: 2104, groups: ["avdelning-b", "gemensam"] }