nfs_server_ip: "192.168.56.10"
nfs_network: "192.168.56.0/24"

groups_to_create:
  - name: alla
    gid: 2000
  - name: avd_a
    gid: 2001
  - name: avd_b
    gid: 2002

users_to_create:
  - name: anna
    uid: 3001
    groups: "alla,avd_a"
  - name: bert
    uid: 3002
    groups: "alla,avd_b"
  - name: clara
    uid: 3003
    groups: "alla,avd_a,avd_b"

shares:
  - name: gemensam
    path: /shares/gemensam
    group: alla
    mode: "2775"

  - name: avdelning-a
    path: /shares/avdelning-a
    group: avd_a
    mode: "2770"

  - name: avdelning-b
    path: /shares/avdelning-b
    group: avd_b
    mode: "2770"

quotas:
  - group: avd_a
    soft: 20480
    hard: 25600

  - group: avd_b
    soft: 20480
    hard: 25600