---
- name: Skapa användare och grupper på alla maskiner
  hosts: all
  become: true
  vars_files:
    - group_vars/all.yml

  tasks:
    - name: Uppdatera apt-cache
      apt:
        update_cache: true
        cache_valid_time: 3600